image: androidsdk/android-31
test:
  script:
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
    - ./gradlew -Pci --console=plain ktlintCheck
    - ./gradlew -Pci --console=plain :app:testDebug
build:
  only:
    - tags
  script:
    - ./gradlew bundleRelease
  artifacts:
    name: "$CI_COMMIT_TAG"
    paths:
      - app/build/outputs/bundle/release/app-release.aab
