name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v4
      - name: Build and sign
        env:
	  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
	run: ./gradlew bundleRelease
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_name }}
          path: app/build/outputs/bundle/release/app-release.aab
	  retention-days: 1